---
title: "Draft initial analyasis"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(scales)
library(cluster)
library(factoextra)
```



```{r}
library(readr)
df <- read_csv("~/fire_arm_checks/data/nics-firearm-background-checks.csv")


# Convert month to date 
df <- df %>%
  mutate(month = ymd(paste0(month, "-01")))

df


```


# US Total Trends
 
```{r}
us_trend <- df %>%
  group_by(month) %>%
  summarise(total_checks = sum(totals, na.rm = TRUE)) %>%
  arrange(month) %>%
  mutate(rolling_avg = zoo::rollmean(total_checks, k = 12, fill = NA, align = "right"))

ggplot(us_trend, aes(x = month)) +
  geom_line(aes(y = total_checks), alpha = 0.4) +
  geom_line(aes(y = rolling_avg), linewidth = 1) +
  labs(title = "US Firearm Background Checks Over Time",
       y = "Total Checks", x = "Year") +
  theme_minimal()
```


## Comparing Top States. 

```{r}

top_states <- df %>%
  group_by(state) %>%
  summarise(total = sum(totals)) %>%
  top_n(6, total) %>%
  pull(state)

df_top <- df %>%
  filter(state %in% top_states) %>%
  group_by(state) %>%
  mutate(index = totals / first(totals) * 100)

ggplot(df_top, aes(x = month, y = index, color = state)) +
  geom_line() +
  labs(title = "Standardised Trends Across Top States",
       y = "Index (Base = 100)", x = "Year") +
  theme_minimal()

```



